MASIVO/config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get "prueba" => "pages#prueba", as: :prueba
  get "about" => "pages#about", as: :about
  get "ranking" => "pages#ranking", as: :ranking
  get "hashtags" => "hashtags#index", as: :hashtags
  get "events" => "events#index", as: :events
  get "adminevents" => "events#index_admin", as: :adminevents

  get 'lectura_tw_stream/index'

  resources :trademarks

  resources :tweets

  resources :review_events

  resources :review_account_events

  resources :key_words_events

  resources :organizations

  resources :hashtags

  resources :events

  resources :evaluations

  resources :evaluation_account_events

  resources :data_tweet_reviews

  resources :data_evaluation_real_times

  resources :data_account_events

  resources :contacts

  resources :batch_deletions

  resources :advertises

  resources :addresses

  resources :accounts

end

MASIVO/app/models/account.rb
class Account < ActiveRecord::Base
	has_one :data_account_event
    has_many :advertises
    has_many :tweets
    has_and_belongs_to_many :tweets #AccountTweet

	belongs_to :data_account_event 
end

MASIVO/app/models/accounts_tweet.rb
class AccountTweet < ActiveRecord::Base
# Un tweet hace referencia a varias cuentas
   belongs_to :account
   belongs_to :tweet
end

MASIVO/app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :organization
end

MASIVO/app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :account
	belongs_to :event
end

MASIVO/app/models/batch_deletion.rb
class BatchDeletion < ActiveRecord::Base
end

MASIVO/app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :organization
end

MASIVO/app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	has_one :data_evaluation_real_time
	has_one :evaluation_account_event

	belongs_to :review_event
	belongs_to :data_evaluation_real_time
	belongs_to :evaluation_account_event
end

MASIVO/app/models/event.rb
class Event < ActiveRecord::Base
   has_many :advertises
   has_one :review_event
   has_many :key_words_event
   has_and_belongs_to_many :organizations #EventOrganization
   has_and_belongs_to_many :hashtags #HashtagEvent
   has_and_belongs_to_many :tweets #EventTweet

   belongs_to :review_event
end

MASIVO/app/models/event_tweet.rb
class EventTweet < ActiveRecord::Base
#Un tweet puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :tweet
end

MASIVO/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :tweets #HashtagTweet 
	has_and_belongs_to_many :events #HashtagEvent
end

MASIVO/app/models/hashtag_event.rb
class HashtagEvent < ActiveRecord::Base
# Un hashtag puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :hashtag
end

MASIVO/app/models/hashtag_tweet.rb
class HashtagTweet < ActiveRecord::Base
# Un tweet puede contener mas de un hashtag
   belongs_to :hashtag
   belongs_to :tweet
end

MASIVO/app/models/key_words_event.rb
class KeyWordsEvent < ActiveRecord::Base
	belongs_to :event
end

MASIVO/app/models/organization.rb
class Organization < ActiveRecord::Base
	has_one :address
	has_one :contact
	has_many :trademarks
    has_and_belongs_to_many :events #EventOrganization
end

MASIVO/app/models/review_event.rb
class ReviewEvent < ActiveRecord::Base
	has_one :event 
	has_one :review_account_event
	has_many :evaluations 

	belongs_to :event
	belongs_to :review_account_event
end

MASIVO/app/models/trademark.rb
class Trademark < ActiveRecord::Base
	belongs_to: organization
end

MASIVO/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	has_one :data_tweet_review
    has_and_belongs_to_many :accounts #AccountTweet
    has_and_belongs_to_many :hashtags #HashtagTweet
    has_and_belongs_to_many :events #EventTweet

    belongs_to :account
    belongs_to :data_tweet_review
end

MASIVO/app/controllers/data_tweet_reviews_controller.rb
class DataTweetReviewsController < ApplicationController
  before_action :set_data_tweet_review, only: [:show, :edit, :update, :destroy]

  # GET /data_tweet_reviews
  # GET /data_tweet_reviews.json
  def index
    @data_tweet_reviews = DataTweetReview.all
  end

  # GET /data_tweet_reviews/1
  # GET /data_tweet_reviews/1.json
  def show
  end

  # GET /data_tweet_reviews/new
  def new
    @data_tweet_review = DataTweetReview.new
  end

  # GET /data_tweet_reviews/1/edit
  def edit
  end

  # POST /data_tweet_reviews
  # POST /data_tweet_reviews.json
  def create
    @data_tweet_review = DataTweetReview.new(data_tweet_review_params)

    respond_to do |format|
      if @data_tweet_review.save
        format.html { redirect_to @data_tweet_review, notice: 'Data tweet review was successfully created.' }
        format.json { render :show, status: :created, location: @data_tweet_review }
      else
        format.html { render :new }
        format.json { render json: @data_tweet_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_tweet_reviews/1
  # PATCH/PUT /data_tweet_reviews/1.json
  def update
    respond_to do |format|
      if @data_tweet_review.update(data_tweet_review_params)
        format.html { redirect_to @data_tweet_review, notice: 'Data tweet review was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_tweet_review }
      else
        format.html { render :edit }
        format.json { render json: @data_tweet_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_tweet_reviews/1
  # DELETE /data_tweet_reviews/1.json
  def destroy
    @data_tweet_review.destroy
    respond_to do |format|
      format.html { redirect_to data_tweet_reviews_url, notice: 'Data tweet review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_tweet_review
      @data_tweet_review = DataTweetReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_tweet_review_params
      params.require(:data_tweet_review).permit(:geo, :state, :geo_cord, :city_tweet, :comuna_tweet, :sensitivity_rank, :tweet_id)
    end
end

MASIVO/app/helpers/data_tweet_reviews_helper.rb
module DataTweetReviewsHelper
end

MASIVO/app/helpers/events_helper.rb
module EventsHelper
end

MASIVO/app/helpers/pages_helper.rb
module PagesHelper
end

MASIVO/app/helpers/tweets_helper.rb
module TweetsHelper
end

MASIVO/app/views/data_tweet_reviews/_form.html.erb
<%= form_for(@data_tweet_review) do |f| %>
  <% if @data_tweet_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_tweet_review.errors.count, "error") %> prohibited this data_tweet_review from being saved:</h2>

      <ul>
      <% @data_tweet_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :geo %><br>
    <%= f.check_box :geo %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.check_box :state %>
  </div>
  <div class="field">
    <%= f.label :geo_cord %><br>
    <%= f.text_field :geo_cord %>
  </div>
  <div class="field">
    <%= f.label :city_tweet %><br>
    <%= f.text_field :city_tweet %>
  </div>
  <div class="field">
    <%= f.label :comuna_tweet %><br>
    <%= f.text_field :comuna_tweet %>
  </div>
  <div class="field">
    <%= f.label :sensitivity_rank %><br>
    <%= f.number_field :sensitivity_rank %>
  </div>
  <div class="field">
    <%= f.label :tweet_id %><br>
    <%= f.number_field :tweet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MASIVO/app/views/data_tweet_reviews/edit.html.erb
<h1>Editing data_tweet_review</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_tweet_review %> |
<%= link_to 'Back', data_tweet_reviews_path %>

MASIVO/app/views/data_tweet_reviews/index.html.erb
<h1>Listing data_tweet_reviews</h1>

<table>
  <thead>
    <tr>
      <th>Geo</th>
      <th>State</th>
      <th>Geo cord</th>
      <th>City tweet</th>
      <th>Comuna tweet</th>
      <th>Sensitivity rank</th>
      <th>Tweet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_tweet_reviews.each do |data_tweet_review| %>
      <tr>
        <td><%= data_tweet_review.geo %></td>
        <td><%= data_tweet_review.state %></td>
        <td><%= data_tweet_review.geo_cord %></td>
        <td><%= data_tweet_review.city_tweet %></td>
        <td><%= data_tweet_review.comuna_tweet %></td>
        <td><%= data_tweet_review.sensitivity_rank %></td>
        <td><%= data_tweet_review.tweet_id %></td>
        <td><%= link_to 'Show', data_tweet_review %></td>
        <td><%= link_to 'Edit', edit_data_tweet_review_path(data_tweet_review) %></td>
        <td><%= link_to 'Destroy', data_tweet_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data tweet review', new_data_tweet_review_path %>

MASIVO/app/views/data_tweet_reviews/new.html.erb
<h1>New data_tweet_review</h1>

<%= render 'form' %>

<%= link_to 'Back', data_tweet_reviews_path %>

MASIVO/app/views/data_tweet_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Geo:</strong>
  <%= @data_tweet_review.geo %>
</p>

<p>
  <strong>State:</strong>
  <%= @data_tweet_review.state %>
</p>

<p>
  <strong>Geo cord:</strong>
  <%= @data_tweet_review.geo_cord %>
</p>

<p>
  <strong>City tweet:</strong>
  <%= @data_tweet_review.city_tweet %>
</p>

<p>
  <strong>Comuna tweet:</strong>
  <%= @data_tweet_review.comuna_tweet %>
</p>

<p>
  <strong>Sensitivity rank:</strong>
  <%= @data_tweet_review.sensitivity_rank %>
</p>

<p>
  <strong>Tweet:</strong>
  <%= @data_tweet_review.tweet_id %>
</p>

<%= link_to 'Edit', edit_data_tweet_review_path(@data_tweet_review) %> |
<%= link_to 'Back', data_tweet_reviews_path %>