MASIVO/config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get "prueba" => "pages#prueba", as: :prueba
  get "about" => "pages#about", as: :about
  get "ranking" => "pages#ranking", as: :ranking
  get "hashtags" => "hashtags#index", as: :hashtags
  get "events" => "events#index", as: :events
  get "adminevents" => "events#index_admin", as: :adminevents

  get 'lectura_tw_stream/index'

  resources :trademarks

  resources :tweets

  resources :review_events

  resources :review_account_events

  resources :key_words_events

  resources :organizations

  resources :hashtags

  resources :events

  resources :evaluations

  resources :evaluation_account_events

  resources :data_tweet_reviews

  resources :data_evaluation_real_times

  resources :data_account_events

  resources :contacts

  resources :batch_deletions

  resources :advertises

  resources :addresses

  resources :accounts

end

MASIVO/app/models/account.rb
class Account < ActiveRecord::Base
	has_one :data_account_event
    has_many :advertises
    has_many :tweets
    has_and_belongs_to_many :tweets #AccountTweet

	belongs_to :data_account_event 
end

MASIVO/app/models/accounts_tweet.rb
class AccountTweet < ActiveRecord::Base
# Un tweet hace referencia a varias cuentas
   belongs_to :account
   belongs_to :tweet
end

MASIVO/app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :organization
end

MASIVO/app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :account
	belongs_to :event
end

MASIVO/app/models/batch_deletion.rb
class BatchDeletion < ActiveRecord::Base
end

MASIVO/app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :organization
end

MASIVO/app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	has_one :data_evaluation_real_time
	has_one :evaluation_account_event

	belongs_to :review_event
	belongs_to :data_evaluation_real_time
	belongs_to :evaluation_account_event
end

MASIVO/app/models/event.rb
class Event < ActiveRecord::Base
   has_many :advertises
   has_one :review_event
   has_many :key_words_event
   has_and_belongs_to_many :organizations #EventOrganization
   has_and_belongs_to_many :hashtags #HashtagEvent
   has_and_belongs_to_many :tweets #EventTweet

   belongs_to :review_event
end

MASIVO/app/models/event_tweet.rb
class EventTweet < ActiveRecord::Base
#Un tweet puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :tweet
end

MASIVO/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :tweets #HashtagTweet 
	has_and_belongs_to_many :events #HashtagEvent
end

MASIVO/app/models/hashtag_event.rb
class HashtagEvent < ActiveRecord::Base
# Un hashtag puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :hashtag
end

MASIVO/app/models/hashtag_tweet.rb
class HashtagTweet < ActiveRecord::Base
# Un tweet puede contener mas de un hashtag
   belongs_to :hashtag
   belongs_to :tweet
end

MASIVO/app/models/key_words_event.rb
class KeyWordsEvent < ActiveRecord::Base
	belongs_to :event
end

MASIVO/app/models/organization.rb
class Organization < ActiveRecord::Base
	has_one :address
	has_one :contact
	has_many :trademarks
    has_and_belongs_to_many :events #EventOrganization
end

MASIVO/app/models/review_event.rb
class ReviewEvent < ActiveRecord::Base
	has_one :event 
	has_one :review_account_event
	has_many :evaluations 

	belongs_to :event
	belongs_to :review_account_event
end

MASIVO/app/models/trademark.rb
class Trademark < ActiveRecord::Base
	belongs_to: organization
end

MASIVO/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	has_one :data_tweet_review
    has_and_belongs_to_many :accounts #AccountTweet
    has_and_belongs_to_many :hashtags #HashtagTweet
    has_and_belongs_to_many :events #EventTweet

    belongs_to :account
    belongs_to :data_tweet_review
end

MASIVO/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.where("type_account = ? OR type_account = ?",1,2)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new 
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
      
    if @account.type_account != 0

    dae = DataAccountEvent.new
    
        client = Twitter::REST::Client.new do |config|
            config.consumer_key       = 'xYEFttTg61yWfZO20byljihWF'
            config.consumer_secret    = 'DLdNpRAgcxsqdODqJP1yTSE7p02T3hSUDF1qMbz14QrVp5jKLO'
            config.oauth_token        = '93945943-Pd4V1IuroSUUU4GsdzUvprQ0or0ZRAajUt8DMPgIb'
            config.oauth_token_secret = 'GZWtSu5QEXmUJUb0ZTEjfdg262DxxX03IljeeCl5PtvhZ'
        end

        p = @account.user_twitter.delete "@"
        c = client.user(p)

        @account.key_user_id = c.id
        @account.user_name = c.name
        @account.save

        dae.id = nil
        dae.url_official = c.website.to_s
        dae.location = c.location
        dae.url_twitter_event = "https://twitter.com/"+p
        dae.num_tweets = c.statuses_count 
        dae.num_photo_and_video = 0
        dae.num_following = c.friends_count
        dae.num_followers = c.followers_count 
        
      if @account.type_account == 1
        dae.account_official = true
      end

        dae.date_creation_account = c.created_at
        dae.account_id = @account.id
        dae.save
        @account.data_account_event_id = dae.id
        
        respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end 

    end

  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
     def data_account_event_params
      params.require(:data_account_event).permit(:location, :url_twitter_event, :url_official, :num_tweets, :num_photo_and_video, :num_following, :num_followers, :account_official, :date_creation_account, :account_id)
    end

    def account_params
      params.require(:account).permit(:key_user_id, :user_twitter, :user_name, :type_account, :data_account_event_id)
    end
end

MASIVO/app/helpers/accounts_helper.rb
module AccountsHelper
end

MASIVO/app/helpers/contacts_helper.rb
module ContactsHelper
end

MASIVO/app/helpers/events_helper.rb
module EventsHelper
end

MASIVO/app/helpers/pages_helper.rb
module PagesHelper
end

MASIVO/app/helpers/tweets_helper.rb
module TweetsHelper
end

MASIVO/app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_twitter %><br>
    <%= f.text_field :user_twitter %>
  </div>
  <div class="field">
    <%= f.label :type_account %><br>
    <%= f.number_field :type_account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MASIVO/app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

MASIVO/app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Key user</th>
      <th>User twitter</th>
      <th>User name</th>
      <th>Type account</th>
      <th>Data account event</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.key_user_id %></td>
        <td><%= account.user_twitter %></td>
        <td><%= account.user_name %></td>
        <td><%= account.type_account %></td>
        <td><%= account.data_account_event_id %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

MASIVO/app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

MASIVO/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key user:</strong>
  <%= @account.key_user_id %>
</p>

<p>
  <strong>User twitter:</strong>
  <%= @account.user_twitter %>
</p>

<p>
  <strong>User name:</strong>
  <%= @account.user_name %>
</p>

<p>
  <strong>Type account:</strong>
  <%= @account.type_account %>
</p>

<p>
  <strong>Data account event:</strong>
  <%= @account.data_account_event_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>