MASIVO/config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get "prueba" => "pages#prueba", as: :prueba
  get "about" => "pages#about", as: :about
  get "ranking" => "pages#ranking", as: :ranking
  get "hashtags" => "hashtags#index", as: :hashtags
  get "events" => "events#index", as: :events
  get "adminevents" => "events#index_admin", as: :adminevents

  get 'lectura_tw_stream/index'

  resources :trademarks

  resources :tweets

  resources :review_events

  resources :review_account_events

  resources :key_words_events

  resources :organizations

  resources :hashtags

  resources :events

  resources :evaluations

  resources :evaluation_account_events

  resources :data_tweet_reviews

  resources :data_evaluation_real_times

  resources :data_account_events

  resources :contacts

  resources :batch_deletions

  resources :advertises

  resources :addresses

  resources :accounts

end

MASIVO/app/models/account.rb
class Account < ActiveRecord::Base
	has_one :data_account_event
    has_many :advertises
    has_many :tweets
    has_and_belongs_to_many :tweets #AccountTweet

	belongs_to :data_account_event 
end

MASIVO/app/models/accounts_tweet.rb
class AccountTweet < ActiveRecord::Base
# Un tweet hace referencia a varias cuentas
   belongs_to :account
   belongs_to :tweet
end

MASIVO/app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :organization
end

MASIVO/app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :account
	belongs_to :event
end

MASIVO/app/models/batch_deletion.rb
class BatchDeletion < ActiveRecord::Base
end

MASIVO/app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :organization
end

MASIVO/app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	has_one :data_evaluation_real_time
	has_one :evaluation_account_event

	belongs_to :review_event
	belongs_to :data_evaluation_real_time
	belongs_to :evaluation_account_event
end

MASIVO/app/models/event.rb
class Event < ActiveRecord::Base
   has_many :advertises
   has_one :review_event
   has_many :key_words_event
   has_and_belongs_to_many :organizations #EventOrganization
   has_and_belongs_to_many :hashtags #HashtagEvent
   has_and_belongs_to_many :tweets #EventTweet

   belongs_to :review_event
end

MASIVO/app/models/event_tweet.rb
class EventTweet < ActiveRecord::Base
#Un tweet puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :tweet
end

MASIVO/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :tweets #HashtagTweet 
	has_and_belongs_to_many :events #HashtagEvent
end

MASIVO/app/models/hashtag_event.rb
class HashtagEvent < ActiveRecord::Base
# Un hashtag puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :hashtag
end

MASIVO/app/models/hashtag_tweet.rb
class HashtagTweet < ActiveRecord::Base
# Un tweet puede contener mas de un hashtag
   belongs_to :hashtag
   belongs_to :tweet
end

MASIVO/app/models/key_words_event.rb
class KeyWordsEvent < ActiveRecord::Base
	belongs_to :event
end

MASIVO/app/models/organization.rb
class Organization < ActiveRecord::Base
	has_one :address
	has_one :contact
	has_many :trademarks
    has_and_belongs_to_many :events #EventOrganization
end

MASIVO/app/models/review_event.rb
class ReviewEvent < ActiveRecord::Base
	has_one :event 
	has_one :review_account_event
	has_many :evaluations 

	belongs_to :event
	belongs_to :review_account_event
end

MASIVO/app/models/trademark.rb
class Trademark < ActiveRecord::Base
	belongs_to: organization
end

MASIVO/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	has_one :data_tweet_review
    has_and_belongs_to_many :accounts #AccountTweet
    has_and_belongs_to_many :hashtags #HashtagTweet
    has_and_belongs_to_many :events #EventTweet

    belongs_to :account
    belongs_to :data_tweet_review
end

MASIVO/app/controllers/key_words_events_controller.rb
class KeyWordsEventsController < ApplicationController
  before_action :set_key_words_event, only: [:show, :edit, :update, :destroy]

  # GET /key_words_events
  # GET /key_words_events.json
  def index
    @key_words_events = KeyWordsEvent.all
  end

  # GET /key_words_events/1
  # GET /key_words_events/1.json
  def show
  end

  # GET /key_words_events/new
  def new
    @key_words_event = KeyWordsEvent.new
  end

  # GET /key_words_events/1/edit
  def edit
  end

  # POST /key_words_events
  # POST /key_words_events.json
  def create
    @key_words_event = KeyWordsEvent.new(key_words_event_params)

    respond_to do |format|
      if @key_words_event.save
        format.html { redirect_to @key_words_event, notice: 'Key words event was successfully created.' }
        format.json { render :show, status: :created, location: @key_words_event }
      else
        format.html { render :new }
        format.json { render json: @key_words_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /key_words_events/1
  # PATCH/PUT /key_words_events/1.json
  def update
    respond_to do |format|
      if @key_words_event.update(key_words_event_params)
        format.html { redirect_to @key_words_event, notice: 'Key words event was successfully updated.' }
        format.json { render :show, status: :ok, location: @key_words_event }
      else
        format.html { render :edit }
        format.json { render json: @key_words_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /key_words_events/1
  # DELETE /key_words_events/1.json
  def destroy
    @key_words_event.destroy
    respond_to do |format|
      format.html { redirect_to key_words_events_url, notice: 'Key words event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_key_words_event
      @key_words_event = KeyWordsEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def key_words_event_params
      params.require(:key_words_event).permit(:palabra, :event_id)
    end
end

MASIVO/app/helpers/accounts_helper.rb
module AccountsHelper
end

MASIVO/app/helpers/events_helper.rb
module EventsHelper
end

MASIVO/app/helpers/key_words_events_helper.rb
module KeyWordsEventsHelper
end

MASIVO/app/helpers/pages_helper.rb
module PagesHelper
end

MASIVO/app/helpers/tweets_helper.rb
module TweetsHelper
end

MASIVO/app/views/key_words_events/_form.html.erb
<%= form_for(@key_words_event) do |f| %>
  <% if @key_words_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key_words_event.errors.count, "error") %> prohibited this key_words_event from being saved:</h2>

      <ul>
      <% @key_words_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :palabra %><br>
    <%= f.text_field :palabra %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MASIVO/app/views/key_words_events/edit.html.erb
<h1>Editing key_words_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @key_words_event %> |
<%= link_to 'Back', key_words_events_path %>

MASIVO/app/views/key_words_events/index.html.erb
<h1>Listing key_words_events</h1>

<table>
  <thead>
    <tr>
      <th>Palabra</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @key_words_events.each do |key_words_event| %>
      <tr>
        <td><%= key_words_event.palabra %></td>
        <td><%= key_words_event.event_id %></td>
        <td><%= link_to 'Show', key_words_event %></td>
        <td><%= link_to 'Edit', edit_key_words_event_path(key_words_event) %></td>
        <td><%= link_to 'Destroy', key_words_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Key words event', new_key_words_event_path %>

MASIVO/app/views/key_words_events/new.html.erb
<h1>New key_words_event</h1>

<%= render 'form' %>

<%= link_to 'Back', key_words_events_path %>

MASIVO/app/views/key_words_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Palabra:</strong>
  <%= @key_words_event.palabra %>
</p>

<p>
  <strong>Event:</strong>
  <%= @key_words_event.event_id %>
</p>

<%= link_to 'Edit', edit_key_words_event_path(@key_words_event) %> |
<%= link_to 'Back', key_words_events_path %>